import cors from "cors";
import express from "express";
import nodemailer from "nodemailer";

const app = express();
const port = Number(process.env.MAILER_PORT || 8787);
const SEND_DELAY_MS = 300;

app.use(cors());
app.use(express.json({ limit: "1mb" }));

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const applyMailVariables = (source, variables) => {
  if (!source) return "";

  return source.replace(/\{+\s*([a-zA-Z0-9_]+)\s*\}+/g, (_, token) => {
    const value = variables[token.toLowerCase()];
    return value ?? "";
  });
};

const escapeHtml = (value) =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");

const buildTemplateHtml = (templateId, subject, body, recipientName) => {
  const paletteByTemplate = {
    rose: { primary: "#f43f5e", glow: "#fb7185" },
    ok: { primary: "#0ea5e9", glow: "#22d3ee" },
    justice: { primary: "#f59e0b", glow: "#fb923c" },
  };

  const palette = paletteByTemplate[templateId] || paletteByTemplate.rose;
  const safeBody = escapeHtml(body).replace(/\n/g, "<br />");
  const safeSubject = escapeHtml(subject);
  const safeName = escapeHtml(recipientName || "Participant");

  return `<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#090f1d;font-family:Segoe UI,Arial,sans-serif;color:#e2e8f0;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:24px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;border-radius:16px;overflow:hidden;border:1px solid #1e293b;background:linear-gradient(140deg,#0b1222,#111827 60%,#0b1222);">
            <tr>
              <td style="padding:22px 28px;border-bottom:1px solid #1f2937;background:radial-gradient(circle at right top,${palette.glow}33,transparent 60%);">
                <p style="margin:0;color:${palette.glow};font-size:11px;letter-spacing:1.6px;text-transform:uppercase;">Luminus Events</p>
                <h1 style="margin:8px 0 0 0;color:#f8fafc;font-size:24px;line-height:1.3;">${safeSubject}</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:26px 28px;">
                <p style="margin:0 0 14px 0;font-size:15px;color:#cbd5e1;">Hi ${safeName},</p>
                <div style="font-size:15px;line-height:1.7;color:#e2e8f0;">${safeBody}</div>
                <p style="margin:22px 0 0 0;font-size:13px;color:#94a3b8;">Generated by Luminus Mail Console.</p>
              </td>
            </tr>
            <tr>
              <td style="height:5px;background:linear-gradient(90deg,${palette.primary},${palette.glow});"></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
};

app.get("/api/health", (_req, res) => {
  res.json({ ok: true, service: "mailer-server" });
});

app.post("/api/send-mails", async (req, res) => {
  const { smtp, recipients, message } = req.body || {};

  if (!smtp || !message || !Array.isArray(recipients)) {
    return res.status(400).json({
      error: "Invalid payload: smtp, message and recipients are required.",
    });
  }

  const host = String(smtp.host || "").trim();
  const port = Number(smtp.port || 0);
  const secure = Boolean(smtp.secure);
  const user = String(smtp.user || "").trim();
  const pass = String(smtp.pass || "");
  const fromEmail = String(smtp.fromEmail || "").trim();
  const fromName = String(smtp.fromName || "Team Luminus").trim();

  if (!host || !port || !user || !pass || !fromEmail) {
    return res.status(400).json({
      error:
        "SMTP host, port, user, password, and fromEmail are required values.",
    });
  }

  const transport = nodemailer.createTransport({
    host,
    port,
    secure,
    auth: {
      user,
      pass,
    },
  });

  try {
    await transport.verify();
  } catch (error) {
    return res.status(400).json({
      error:
        error instanceof Error
          ? `SMTP verification failed: ${error.message}`
          : "SMTP verification failed.",
    });
  }

  const subjectTemplate = String(message.subjectTemplate || "");
  const bodyTemplate = String(message.bodyTemplate || "");
  const templateId = String(message.templateId || "rose").toLowerCase();

  const results = await Promise.allSettled(
    recipients.map(async (recipient, index) => {
      const email = String(recipient.email || "").trim();
      if (!email) {
        throw new Error("recipient email is missing");
      }

      await delay(index * SEND_DELAY_MS);

      const variables = {
        name: String(recipient.name || "Participant"),
        studentid: String(recipient.studentId || ""),
        email,
        event: String(recipient.event || "Luminus Event"),
        transactionid: String(recipient.transactionId || ""),
      };

      const personalizedSubject = applyMailVariables(
        subjectTemplate,
        variables,
      );
      const personalizedBody = applyMailVariables(bodyTemplate, variables);
      const html = buildTemplateHtml(
        templateId,
        personalizedSubject,
        personalizedBody,
        variables.name,
      );

      await transport.sendMail({
        from: `"${fromName}" <${fromEmail}>`,
        to: email,
        subject: personalizedSubject,
        text: personalizedBody,
        html,
      });

      return { email };
    }),
  );

  const errors = [];
  let sent = 0;

  results.forEach((result, index) => {
    if (result.status === "fulfilled") {
      sent += 1;
      return;
    }

    const email = String(recipients[index]?.email || "unknown");
    const reason =
      result.reason instanceof Error
        ? result.reason.message
        : "Unknown send failure.";

    errors.push({ email, reason });
  });

  return res.status(200).json({
    attempted: recipients.length,
    sent,
    failed: recipients.length - sent,
    errors,
  });
});

app.listen(port, () => {
  console.log(`Mailer server running on http://localhost:${port}`);
});
