import * as XLSX from "xlsx";

import type {
  ParticipantDetail,
  RegistrationRow,
  UploadedSheet,
  VerificationLog,
} from "./types";

export const PERSONALIZATION_VARIABLES = [
  "{name}",
  "{studentId}",
  "{email}",
  "{event}",
  "{transactionId}",
];

const normalizeHeader = (header: string) =>
  header.trim().toLowerCase().replace(/\s+/g, "_");

export const textValue = (value: unknown): string => {
  if (value === null || value === undefined) return "";
  return String(value).trim();
};

const normalizeStudentId = (value: unknown): string =>
  textValue(value).replace(/\s+/g, "").toUpperCase();

export const truncateText = (value: unknown, maxLength = 80): string => {
  const raw = textValue(value);
  if (raw.length <= maxLength) return raw;
  return `${raw.slice(0, Math.max(maxLength - 3, 1)).trimEnd()}...`;
};

export const applyMailVariables = (
  source: string,
  variables: Record<string, string>,
): string => {
  if (!source) return "";

  return source.replace(/\{+\s*([a-zA-Z0-9_]+)\s*\}+/g, (_, token: string) => {
    const value = variables[token.toLowerCase()];
    return value ?? "";
  });
};

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

export const buildTemplateHtml = (
  subject: string,
  body: string,
  recipientName: string,
): string => {
  const safeBody = escapeHtml(body).replace(/\n/g, "<br />");
  const safeSubject = escapeHtml(subject);
  const safeName = escapeHtml(recipientName || "Participant");

  return `<!doctype html>
<html>
  <body style="margin:0;padding:0;background:#090f1d;font-family:Segoe UI,Arial,sans-serif;color:#e2e8f0;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:24px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;border-radius:16px;overflow:hidden;border:1px solid #1e293b;background:linear-gradient(140deg,#0b1222,#111827 60%,#0b1222);">
            <tr>
              <td style="padding:22px 28px;border-bottom:1px solid #1f2937;background:radial-gradient(circle at right top,#fb923c33,transparent 60%);">
                <p style="margin:0;color:#fb923c;font-size:11px;letter-spacing:1.6px;text-transform:uppercase;">Luminus Events</p>
                <h1 style="margin:8px 0 0 0;color:#f8fafc;font-size:24px;line-height:1.3;">${safeSubject}</h1>
              </td>
            </tr>
            <tr>
              <td style="padding:26px 28px;">
                <p style="margin:0 0 14px 0;font-size:15px;color:#cbd5e1;">Hi ${safeName},</p>
                <div style="font-size:15px;line-height:1.7;color:#e2e8f0;">${safeBody}</div>
                <p style="margin:22px 0 0 0;font-size:13px;color:#94a3b8;">Generated by Luminus Mail Console.</p>
              </td>
            </tr>
            <tr>
              <td style="height:5px;background:linear-gradient(90deg,#f59e0b,#fb923c);"></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
};

const normalizeEventName = (value: unknown): string =>
  textValue(value)
    .toLowerCase()
    .replace(/\s*-\s*rs\.?\s*\d+(\.\d+)?/gi, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

const EVENT_EQUIVALENCE_OVERRIDES = new Set([
  "solaris x::developer tools engineering productivity",
]);

const areEventsEquivalent = (
  billdeskEvent: unknown,
  supabaseEvent: unknown,
): boolean => {
  const left = normalizeEventName(billdeskEvent);
  const right = normalizeEventName(supabaseEvent);

  if (!left || !right) return false;
  if (left === right) return true;

  if (
    EVENT_EQUIVALENCE_OVERRIDES.has(`${left}::${right}`) ||
    EVENT_EQUIVALENCE_OVERRIDES.has(`${right}::${left}`)
  ) {
    return true;
  }

  const shorter = left.length <= right.length ? left : right;
  const longer = left.length > right.length ? left : right;

  const shorterWords = shorter.split(" ").filter(Boolean);
  const longerWords = longer.split(" ").filter(Boolean);
  const longerWordSet = new Set(longerWords);

  if (
    shorterWords.length === 1 &&
    shorterWords[0].length >= 3 &&
    longerWordSet.has(shorterWords[0])
  ) {
    return true;
  }

  if (shorter.length >= 6 && longer.includes(shorter)) return true;

  return false;
};

const pickFirstValue = (
  row: Record<string, unknown>,
  keys: string[],
): string => {
  for (const key of keys) {
    const found = textValue(row[key]);
    if (found) return found;
  }
  return "";
};

const parseSpreadsheetFromBuffer = (
  buffer: ArrayBuffer,
  fileName: string,
  skipFirstHeaderRow = false,
): UploadedSheet => {
  const workbook = XLSX.read(buffer, { type: "array" });
  const firstSheetName = workbook.SheetNames[0];

  if (!firstSheetName) {
    throw new Error("Spreadsheet has no sheet.");
  }

  const worksheet = workbook.Sheets[firstSheetName];
  let rawRows: Record<string, unknown>[];

  if (skipFirstHeaderRow) {
    const allRows = XLSX.utils.sheet_to_json<unknown[]>(worksheet, {
      header: 1,
      defval: "",
    });

    if (allRows.length < 3) {
      throw new Error("Spreadsheet has insufficient rows.");
    }

    const headerRow = (allRows[1] as unknown[]).map(String);
    rawRows = (allRows.slice(2) as unknown[][]).map((row) => {
      const record: Record<string, unknown> = {};
      headerRow.forEach((header, index) => {
        record[header] = row[index] ?? "";
      });
      return record;
    });
  } else {
    rawRows = XLSX.utils.sheet_to_json<Record<string, unknown>>(worksheet, {
      defval: "",
    });
  }

  if (!rawRows.length) {
    throw new Error("Spreadsheet is empty. Add at least one data row.");
  }

  const normalizedRows = rawRows.map((row) => {
    const normalized: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(row)) {
      normalized[normalizeHeader(key)] = value;
    }
    return normalized;
  });

  const headers = new Set<string>();
  normalizedRows.forEach((row) => {
    Object.keys(row).forEach((key) => headers.add(key));
  });

  return {
    fileName,
    rowCount: normalizedRows.length,
    headers: Array.from(headers),
    rows: normalizedRows,
  };
};

export const parseSpreadsheet = async (
  file: File,
  skipFirstHeaderRow = false,
): Promise<UploadedSheet> => {
  const buffer = await file.arrayBuffer();
  return parseSpreadsheetFromBuffer(buffer, file.name, skipFirstHeaderRow);
};

export const loadSheetFromUrl = async (
  url: string,
  skipFirstHeaderRow = false,
): Promise<UploadedSheet> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.statusText}`);
  }

  if (url.toLowerCase().endsWith(".json")) {
    const json = await response.json();
    if (!json || typeof json !== "object") {
      throw new Error(`Invalid JSON in ${url}`);
    }

    const source = json as {
      fileName?: unknown;
      rowCount?: unknown;
      headers?: unknown;
      rows?: unknown;
    };

    if (!Array.isArray(source.rows)) {
      throw new Error(`JSON file ${url} does not include rows[]`);
    }

    const rows = source.rows.map((row) => {
      if (!row || typeof row !== "object") return {};
      const normalized: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(
        row as Record<string, unknown>,
      )) {
        normalized[normalizeHeader(key)] = value;
      }
      return normalized;
    });

    const headerSet = new Set<string>();
    rows.forEach((row) => {
      Object.keys(row).forEach((key) => headerSet.add(key));
    });

    return {
      fileName: textValue(source.fileName) || (url.split("/").pop() ?? url),
      rowCount: Number(source.rowCount) || rows.length,
      headers: Array.from(headerSet),
      rows,
    };
  }

  const buffer = await response.arrayBuffer();
  const fileName = url.split("/").pop() ?? url;
  return parseSpreadsheetFromBuffer(buffer, fileName, skipFirstHeaderRow);
};

const parseParticipantsField = (
  participantsRaw: unknown,
): { participants: ParticipantDetail[]; error: string } => {
  if (
    participantsRaw === null ||
    participantsRaw === undefined ||
    participantsRaw === ""
  ) {
    return { participants: [], error: "participants field is empty" };
  }

  let parsed: unknown;

  try {
    parsed =
      typeof participantsRaw === "string"
        ? JSON.parse(participantsRaw)
        : participantsRaw;
  } catch {
    return { participants: [], error: "participants JSON parsing failed" };
  }

  let participantsSource: unknown[] = [];

  if (Array.isArray(parsed)) {
    participantsSource = parsed;
  } else if (
    parsed &&
    typeof parsed === "object" &&
    Array.isArray((parsed as { participants?: unknown }).participants)
  ) {
    participantsSource = (parsed as { participants: unknown[] }).participants;
  } else {
    return {
      participants: [],
      error:
        "participants JSON is not an array and does not contain participants[]",
    };
  }

  const participants = participantsSource.map((entry) => {
    const record =
      entry && typeof entry === "object"
        ? (entry as Record<string, unknown>)
        : {};

    return {
      name: pickFirstValue(record, ["name", "participant_name"]),
      studentId: pickFirstValue(record, ["studentId", "student_id", "usn"]),
      email: pickFirstValue(record, ["email", "email_id"]),
      phoneNumber: pickFirstValue(record, [
        "phoneNumber",
        "phone_number",
        "mobile_no",
      ]),
      participantNumber: pickFirstValue(record, [
        "participantNumber",
        "participant_number",
      ]),
      event: pickFirstValue(record, ["event", "event_name"]),
    };
  });

  return { participants, error: "" };
};

const buildRegistrationRows = (
  supabaseSheet: UploadedSheet,
): { rows: RegistrationRow[]; invalidRows: number } => {
  let invalidRows = 0;

  const rows = supabaseSheet.rows.map((row, index) => {
    const registrationId =
      pickFirstValue(row, ["id", "registration_id", "event_id"]) ||
      `row-${index + 1}`;

    const eventName = pickFirstValue(row, ["event_name", "event", "event_key"]);
    const { participants, error } = parseParticipantsField(row.participants);

    if (error) {
      invalidRows += 1;
    }

    return {
      registrationId,
      eventName,
      participants,
    };
  });

  return { rows, invalidRows };
};

export const verifyTransactionSheets = (
  billdeskSheet: UploadedSheet,
  supabaseSheet: UploadedSheet,
): { logs: VerificationLog[]; invalidRows: number } => {
  const { rows: supabaseRegistrations, invalidRows } =
    buildRegistrationRows(supabaseSheet);

  const logs = billdeskSheet.rows.map((transactionRow) => {
    const transactionId = pickFirstValue(transactionRow, [
      "transaction_ref_no",
      "transaction_id",
      "txn_id",
    ]);

    const studentId = pickFirstValue(transactionRow, [
      "student_id",
      "studentid",
      "usn",
    ]);
    const billdeskEvent = pickFirstValue(transactionRow, [
      "event_name",
      "event",
    ]);
    const billdeskName = pickFirstValue(transactionRow, [
      "team_leader_name",
      "name",
    ]);
    const billdeskEmail = pickFirstValue(transactionRow, ["email_id", "email"]);

    if (!studentId) {
      return {
        transactionId,
        studentId: "",
        billdeskEvent,
        billdeskName,
        billdeskEmail,
        verificationStatus: "FAILED" as const,
        reason: "Stopped: BillDesk row has no student ID.",
        registrationsScanned: supabaseRegistrations.length,
        participantsScanned: 0,
        matchesByStudent: 0,
        matchesByStudentAndEvent: 0,
        matchedRegistrationId: "",
        matchedEvent: "",
        matchedParticipants: [],
      };
    }

    if (!billdeskEvent) {
      return {
        transactionId,
        studentId,
        billdeskEvent: "",
        billdeskName,
        billdeskEmail,
        verificationStatus: "FAILED" as const,
        reason: "Stopped: BillDesk row has no event name.",
        registrationsScanned: supabaseRegistrations.length,
        participantsScanned: 0,
        matchesByStudent: 0,
        matchesByStudentAndEvent: 0,
        matchedRegistrationId: "",
        matchedEvent: "",
        matchedParticipants: [],
      };
    }

    let participantsScanned = 0;
    const studentMatches: Array<{
      registration: RegistrationRow;
      participant: ParticipantDetail;
    }> = [];

    for (const registration of supabaseRegistrations) {
      for (const participant of registration.participants) {
        participantsScanned += 1;

        if (
          normalizeStudentId(participant.studentId) ===
          normalizeStudentId(studentId)
        ) {
          studentMatches.push({ registration, participant });
        }
      }
    }

    if (!studentMatches.length) {
      return {
        transactionId,
        studentId,
        billdeskEvent,
        billdeskName,
        billdeskEmail,
        verificationStatus: "FAILED" as const,
        reason:
          "Stopped: Student ID not found in any Supabase registration participants list.",
        registrationsScanned: supabaseRegistrations.length,
        participantsScanned,
        matchesByStudent: 0,
        matchesByStudentAndEvent: 0,
        matchedRegistrationId: "",
        matchedEvent: "",
        matchedParticipants: [],
      };
    }

    const studentAndEventMatches = studentMatches.filter(
      ({ registration, participant }) => {
        const participantEvent = participant.event || registration.eventName;
        return areEventsEquivalent(billdeskEvent, participantEvent);
      },
    );

    if (!studentAndEventMatches.length) {
      const globalEventMatches = supabaseRegistrations.filter((registration) =>
        areEventsEquivalent(billdeskEvent, registration.eventName),
      );

      if (studentMatches.length > 0 && globalEventMatches.length > 0) {
        const chosenStudentRegistration = studentMatches[0].registration;
        return {
          transactionId,
          studentId,
          billdeskEvent,
          billdeskName,
          billdeskEmail,
          verificationStatus: "VERIFIED" as const,
          reason:
            "Verified (split evidence): student ID exists in Supabase and event exists in Supabase, but not in the same registration row. Please review this transaction manually.",
          registrationsScanned: supabaseRegistrations.length,
          participantsScanned,
          matchesByStudent: studentMatches.length,
          matchesByStudentAndEvent: 0,
          matchedRegistrationId: chosenStudentRegistration.registrationId,
          matchedEvent: chosenStudentRegistration.eventName,
          matchedParticipants: chosenStudentRegistration.participants,
        };
      }

      const matchedEvents = Array.from(
        new Set(
          studentMatches
            .map(
              ({ registration, participant }) =>
                participant.event || registration.eventName,
            )
            .filter(Boolean),
        ),
      );

      return {
        transactionId,
        studentId,
        billdeskEvent,
        billdeskName,
        billdeskEmail,
        verificationStatus: "FAILED" as const,
        reason:
          matchedEvents.length > 0
            ? `Stopped: Student ID matched but event mismatch. Supabase event(s): ${matchedEvents.join(", ")}`
            : "Stopped: Student ID matched but no event value was available in Supabase row.",
        registrationsScanned: supabaseRegistrations.length,
        participantsScanned,
        matchesByStudent: studentMatches.length,
        matchesByStudentAndEvent: 0,
        matchedRegistrationId: "",
        matchedEvent: "",
        matchedParticipants: [],
      };
    }

    const chosen = studentAndEventMatches[0];

    return {
      transactionId,
      studentId,
      billdeskEvent,
      billdeskName,
      billdeskEmail,
      verificationStatus: "VERIFIED" as const,
      reason:
        "Verified: Student ID and event both matched in Supabase participants list.",
      registrationsScanned: supabaseRegistrations.length,
      participantsScanned,
      matchesByStudent: studentMatches.length,
      matchesByStudentAndEvent: studentAndEventMatches.length,
      matchedRegistrationId: chosen.registration.registrationId,
      matchedEvent: chosen.registration.eventName,
      matchedParticipants: chosen.registration.participants,
    };
  });

  return { logs, invalidRows };
};
