-- ============================================================================
-- Create the event-images storage bucket
-- ----------------------------------------------------------------------------
-- Discovered missing entirely on this project while wiring up poster upload +
-- AI auto-extraction: no bucket existed for event/competition posters or the
-- QR PNGs generated by send-ticket-email. Public read (posters/QRs need to
-- render in emails and on the public site), admin-only write (matches the
-- tightened policy intent from the earlier storage RLS fix — no per-user
-- folder scheme needed since only admins upload event/competition media).
-- ============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('event-images', 'event-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY event_images_public_read ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'event-images');

CREATE POLICY event_images_admin_write ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'event-images' AND public.has_role(auth.uid(), 'admin'));

CREATE POLICY event_images_admin_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'event-images' AND public.has_role(auth.uid(), 'admin'));

CREATE POLICY event_images_admin_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'event-images' AND public.has_role(auth.uid(), 'admin'));

-- send-ticket-email uploads QR PNGs using the service-role key, which
-- bypasses RLS entirely, so it's unaffected by the admin-only policies above.
